### ISSUE TITLE
Are build hooks executed on dockerhub ? Getting python errors

### ISSUE THREAD

**Issue by aprixon01112017** [docker/hub-feedback#1343]
/hooks/build:
`#!/bin/bash

docker build -t $IMAGE_NAME .`

Output:

`Executing build hook...
Unexpected error
Encountered error: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/stage/builder/runner.py", line 288, in _run
    self.build()
  File "/stage/builder/runner.py", line 212, in build
    self._build()
  File "/stage/builder/runner.py", line 194, in _build
    if not hooks.run('build'):
  File "/stage/builder/hooks.py", line 21, in run
    utils.execute_command(hook_path, '{} hook failed!'.format(name))
  File "/stage/builder/utils.py", line 43, in execute_command
    bufsize=1)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

What's going on here?

**Comment by lilith** [comment]
I'm having the same issue

**Comment by hgulamabbass** [comment]
Don't know if you solved the issue. I faced the same today it ended up being a Unix Line Ending issue. If your scripts are created in Windows check and see if the line endings are in Windows or Unix format. As Windows line endings cause script issues when run in Linux. Let me know if you struggle.
