### ISSUE TITLE
The type initializer for 'System.Drawing.GDIPlus' threw an exception 

### ISSUE THREAD

**Issue by RajanBabu1** [docker/hub-feedback#1520]
Hi everyone,

Am working on the .net core project in our project there is a requirement to process the pdf file and extracting text from it.

I used the following DLL's in my project,
1. System.Drawing.Common
2. CoreCompat.System.Drawing

**My Docker File:**

FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

**copy csproj and restore as distinct layers**
COPY *.csproj ./ ./
RUN dotnet restore

**copy everything else and build**
COPY ./ ./
RUN dotnet publish -c Debug -o out

**build runtime image**
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/OCRFormProcessing/out .
ENTRYPOINT ["dotnet", "OcrFormProcessing.dll"]

And it works fine on the local machine. But after dockerizing when using the image I get the below issue in both Windows and Linux container.

Please provide me some solution to fix this issue. If it's a docker file issue please share me a sample docker steps to fix the issue. 

Thanks in advance.

**at System.Drawing.GDIPlus.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0, IntPtr& bmp)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at PDFReader.Page.RenderPage(PDFReferenceObject ro, RectangleF rect, Reader reader) in /app/PDFReader/Page.cs:line 113
   at BusinessAccess.CommonExtractPdf.PdfExtractWord(Byte[] pdfFile, String _appsettings, String rootPath) in /app/BusinessAccess/CommonExtractPdf.cs:line 133
   at BusinessAccess.ClaimBusiness.<UpdateClaimPDFBusiness>d__27.MoveNext() in /app/BusinessAccess/ClaimBusiness.cs:line 660
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BusinessAccess.ClaimBusiness.<UpdateStructureJsonBusinessAsync>d__24.MoveNext() in /app/BusinessAccess/ClaimBusiness.cs:line 601
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OCRFormProcessing.Controllers.ClaimController.<ClaimOCRFormProcessAsync>d__20.MoveNext() in /app/OcrFormProcessing/Controllers/ClaimController.cs:line 464**

**Comment by JohnGalt1717** [comment]
Make sure you have the right apt get packages installed per issue per here: https://github.com/dotnet/dotnet-docker/issues/618
