### ISSUE TITLE
Error: /usr/src/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header

### ISSUE THREAD

**Issue by nadav-theguild** [docker/hub-feedback#1577]
I am using WebStorm IDE, React and Docker to run my environment on windows 10.
I have excluded node_modules (as copying windows modules to linux can cause the problem above)
I have tried to delete the node_modules from the container but couldnt get access to remove the folder (used - docker exec -it <mycontainer> bash).

What other analysis can i do? how can i be sure that the modules were created on linux and not windows?

Error below 

nodemon] 1.18.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --inspect server.js`
Debugger listening on ws://127.0.0.1:9229/4bfcf1f7-1b69-4730-820e-09a035ce15e5
For help see https://nodejs.org/en/docs/inspector
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/src/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/services/user.js:2:16)
    at Module._compile (module.js:652:30)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
