### ISSUE TITLE
Can't set up any new autobuilds (from github): Gateway Time-out

### ISSUE THREAD

**Issue by anguslees** [docker/hub-feedback#1813]
I have been unable to create new automated builds on hub.docker for several months.  Every time I try, I get a 504.  I have taken to using travis-ci or other 3rd-party build bots just to run docker build+push, but that is becoming boring for trivial cases.

Eg: when I click on the "Link to GitHub [Connected]" button in https://cloud.docker.com/repository/docker/anguslees/ipdr/builds, I get this response in the browser:

```
Build configurations

Automated build from GitHub or Bitbucket

Fetch source repositories failed. 

Connect your GitHub or Bitbucket account to enable automated builds from your code repositories. If it is already connected, please re-link the source provider.
Link source providers
```

(I have re-linked my github account many times, with no change.)

The javascript console corresponding to the above says:

```
Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
Unhandled rejection ActionableError: cannot GET https://cloud.docker.com/api/build/v1/source/github/orgs/ (504)
    at t (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:308002)
    at new t (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:308533)
    at r (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:451081)
    at https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:437988
    at Array.forEach (<anonymous>)
    at s (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:437959)
    at https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:438562
    at o (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:664110)
    at o._settlePromiseFromHandler (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:637516)
    at o._settlePromise (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:638316)
    at o._settlePromise0 (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:639015)
    at o._settlePromises (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:640231)
    at https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:593889
From previous event:
    at o.h [as _captureStackTrace] (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:601589)
    at o._then (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:632963)
    at o.then (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:631319)
    at t.value (https://d36jcksde1wxzq.cloudfront.net/cloud/swarm.7c58640….js:1:1300023)
    at c.performInitialMount (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:428824)
    at c.mountComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:427992)
    at Object.mountComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:480321)
    at c.performInitialMount (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:429107)
    at c.mountComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:427992)
    at Object.mountComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:480321)
    at Object.updateChildren (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:425600)
    at m._reconcilerUpdateChildren (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:456254)
    at m._updateChildren (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:457003)
    at m.updateChildren (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:456901)
    at m._updateDOMChildren (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:443721)
    at m.updateComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:441945)
    at m.receiveComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:441498)
    at Object.receiveComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:480715)
    at c._updateRenderedComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:432433)
    at c._performComponentUpdate (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:432194)
    at c.updateComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:431472)
    at c.receiveComponent (https://d36jcksde1wxzq.cloudfront.net/cloud/vendor_dashboard.83dbed4….js:1:430589)
```

I have lots of github projects, accumulated over many years.  Is it possible I have too many for docker hub to handle?

**Comment by giner** [comment]
I'm probably having a similar issue here. I found this https://success.docker.com/article/i-have-issues-triggering-autobuilds however it didn't help.

---
![Screenshot from 2019-05-24 22-14-36](https://user-images.githubusercontent.com/533434/58330427-d2875700-7e71-11e9-925e-c3a6e80361d5.png)

---
![Screenshot from 2019-05-24 22-13-43](https://user-images.githubusercontent.com/533434/58330429-d2875700-7e71-11e9-995a-805af786903a.png)

**Comment by anguslees** [comment]
@giner the error you quoted says "403 forbidden" which is quite likely a different cause, even though it presents with similar symptoms.
