### ISSUE TITLE
mongodb not connected with my nodejs code : 'MongoNetworkError',   [Symbol(mongoErrorContextSymbol)]: {} 

### ISSUE THREAD

**Issue by NutonC** [docker/hub-feedback#1967]
## Problem description
I have faced a problem with MongoDB
I created a MongoDB atlas and connect with mongo URI: but it shows only>>
I try to best for fixed it but I loose please help me guys>>>

  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {} }

my javascript code is given below>>
my **index.js**>>
const express=require('express')
const morgan=require('morgan')
const mongoose=require('mongoose')

//import routes

const authRoutes=require('./routes/authRoutes')

const app=express()

// set up view engin
app.set('view engine', 'ejs')
app.set('views', 'views')

//Middleware array

const middleware = [
    morgan('dev'),
    express.static('public'),
    express.urlencoded({extended:true}),
    express.json()
]

app.use(middleware)

app.use('/auth',authRoutes)

app.get('/',(req,res)=>{

   
    res.json({
        message:'Hello world'
    })
})

// pass: pass@01! encode:pass%4001%21
const PORT=process.env.PORT || 3200
mongoose.connect('mongodb+srv://nuton121:nuton0155@cluster0-nomva.mongodb.net/test?retryWrites=true&w=majority',{useNewUrlParser:true})
    .then(()=>{
        app.listen(PORT,()=>{
            console.log(`This server is running on ${PORT}`)
        })
    })
    .catch(e=>{
        return console.log(e)
    })

And In the result by using npm start in the cmd>>>>>

(node:11004) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
{ MongoNetworkError: failed to connect to server [cluster0-shard-00-00-nomva.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to cluster0-shard-00-00-nomva.mongodb.net:27017 closed]
    at Pool.<anonymous> (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\topologies\server.js:438:11)
    at Pool.emit (events.js:198:13)
    at createConnection (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\connection\pool.js:561:14)
    at connect (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\connection\pool.js:1008:9)
    at callback (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\connection\connect.js:97:5)
    at runCommand (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\connection\connect.js:124:7)
    at _callback (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\connection\connect.js:349:5)
    at Connection.errorHandler (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\connection\connect.js:365:5)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at TLSSocket.<anonymous> (C:\Users\Nuton Chakma\Desktop\express\node_modules\mongodb\lib\core\connection\connection.js:370:12)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at _handle.close (net.js:606:12)
    at TCP.done (_tls_wrap.js:388:7)
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {} }

Guys please help me for these issues>>>>

**Comment by NutonC** [comment]
problem solved
