### ISSUE TITLE
MongoNetworkError TransientTransactionError

### ISSUE THREAD

**Issue by evanskarangu** [docker/hub-feedback#1972]
This is how my terminal looks like when i run the command **npm run dev**
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Zip files\react-youtube-app> **npm run dev**

react-boiler-plate@1.0.0 dev C:\Zip files\react-youtube-app
concurrently "npm run backend" "npm run start --prefix client"

[1]
[1] > client@1.0.0 start C:\Zip files\react-youtube-app\client
[1] > react-scripts start
[1]
[0]
[0] > react-boiler-plate@1.0.0 backend C:\Zip files\react-youtube-app
[0] > nodemon server/index.js
[0]
[1] '****react-scripts' is not recognized as an internal or external command,
[1] operable program or batch file.** 
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! client@1.0.0 start: react-scripts start
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the client@1.0.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR! C:\Users\evans\AppData\Roaming\npm-cache_logs\2020-04-03T16_45_45_942Z-debug.log
[1] npm run start --prefix client exited with code 1
[0] [nodemon] 1.19.4
[0] [nodemon] to restart at any time, enter rs
[0] [nodemon] watching dir(s): .
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting node server/index.js
[0] Server Running at 5000
[0] **MongoError: bad auth Authentication failed.**
[0] at C:\Zip files\react-youtube-app\node_modules\mongodb\lib\core\auth\auth_provider.js:46:25
[0] at C:\Zip files\react-youtube-app\node_modules\mongodb\lib\core\auth\scram.js:215:18
[0] at Connection.messageHandler (C:\Zip files\react-youtube-app\node_modules\mongodb\lib\core\connection\connect.js:334:5)
[0] at Connection.emit (events.js:223:5)
[0] at processMessage (C:\Zip files\react-youtube-app\node_modules\mongodb\lib\core\connection\connection.js:364:10)
[0] at TLSSocket. (C:\Zip files\react-youtube-app\node_modules\mongodb\lib\core\connection\connection.js:533:15)
[0] at TLSSocket.emit (events.js:223:5)
[0] at addChunk (_stream_readable.js:309:12)
[0] at readableAddChunk (_stream_readable.js:290:11)
[0] at TLSSocket.Readable.push (_stream_readable.js:224:10)
[0] at TLSWrap.onStreamRead (internal/stream_base_commons.js:181:23) **{
[0] name: 'MongoNetworkError',
[0] errorLabels: [ 'TransientTransactionError' ],
[0] [Symbol(mongoErrorContextSymbol)]: {}
[0] }**
**what I have highlighted is the issue at hand.**
**whitelisting IP adresss doesn't work and also I have done npm install**
Kindly help

**Comment by nebuk89** [comment]
Closing due to lack of activity.
