### ISSUE TITLE
Can't delete tag from private repo, either thru browser or API

### ISSUE THREAD

**Issue by keanR1** [docker/hub-feedback#2251]
## Problem description

Yesterday I could delete tags; today I can't.

**In browser:**

- Go to repo
- Click Tags
- Check boxes next to tag(s)
-  Hit Delete

Page refreshes, but tags remain; Chrome shows 500s (see screenshot below):

- Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
/v2/repositories/.../.../tags/.../:1
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
- /v2/repositories/.../.../tags/.../:1
- Uncaught (in promise) Error: Some promises were rejected main.ac86dabcf8ec8cbbe6ca.js:125 
    at a (main.ac86dabcf8ec8cbbe6ca.js:125:848345)
    at main.ac86dabcf8ec8cbbe6ca.js:125:848580

**On Linux command line:**

```
CRED=$(printf '{"username": "%s", "password": "%s"}' ${USER} ${AUTH})
TOKEN=$(curl -s -H 'Content-Type: application/json' -X POST -d "${CRED}"  https://hub.docker.com/v2/users/login | jq -r .token)
 ```

With the token, listing tags works:

```
curl -H "Authorization: Bearer ${TOKEN}" -fsSL https://hub.docker.com/v2/repositories/${ORG}/${REPO}/tags
```
But deleting a tag doesn't:

```
curl -H "Authorization: Bearer ${TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/${ORG}/${REPO}/tags/${TAG}/"
 ```
 
 If I authenticate with a PAT, I get the result below (as in #2127?)
 
 ```
 {"detail": "access is forbidden with a JWT issued from a personal access token"}
 ```
 
 If I use my password, I get:
 
 ```
 {"detail": "Failed to remove tag."}
 ```

## Debug Information
**Browser name and version**: Chrome Version 103.0.5060.53 (Official Build) (64-bit)

https://hub.docker.com/repository/docker/MY_ORG/MY_REPO/tags?page=1&ordering=last_updated

**Timestamp or time range**: 
`2022-06-29T22:05:32-04:00`
It's been going on all day today.

**Hub Username**:
keanr1

## Screenshots of the issue (if applicable)
![image](https://user-images.githubusercontent.com/103465456/176571717-d806ee21-f505-4baa-ba6a-14aa09d15286.png)

**Comment by milosgajdos** [comment]
Hi, @keanR1 thanks for letting us know. We've now identified the issue and working on the fix.

**Comment by milosgajdos** [comment]
@keanR1 we believe we've now fixed the issue. Could you please verify everything works for you again?

**Comment by keanR1** [comment]
Hi Milos -- Working fine now, thanks!

**Comment by milosgajdos** [comment]
Apologies for the inconvenience. I'll close this ticket now. Please feel free to reopen.

**Comment by cromero251290** [comment]
Hey this is happening to me too

**Comment by milosgajdos** [comment]
@cromero251290 can you give us the namespace/repo this is failing for you on?

**Comment by cromero251290** [comment]
wreckedromero/wreckingball-aem-repository

**Comment by cromero251290** [comment]
![image](https://user-images.githubusercontent.com/106993360/180235010-de7c8d7e-5ddc-472b-867d-383f9f85e806.png)

**Comment by milosgajdos** [comment]
Hey @cromero251290 we've rolled out a change. Can you please if this works for you now?

**Comment by andreisucman** [comment]
Hello, this is happening to me as well. Can you please help? sunchainltd/purrma-jobs
