### ISSUE TITLE
Docker Hub does not render when cookies are disabled

### ISSUE THREAD

**Issue by OiYouYeahYou** [docker/hub-feedback#2266]
## Problem description

Docker Hub does not render any information to people with cookies disabled. This has happened before #2203

## Error messages (on screen or in browser console)

```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at Object.get (/main.67d20ef09a98b096d093.js:2:62930)
    at new e (/main.67d20ef09a98b096d093.js:2:60302)
    at new e (/main.67d20ef09a98b096d093.js:2:71541)
    at /main.67d20ef09a98b096d093.js:2:92114
    at Object.hi [as useState] (/main.67d20ef09a98b096d093.js:152:1984768)
    at t.useState (/main.67d20ef09a98b096d093.js:152:2328278)
    at Ua (/main.67d20ef09a98b096d093.js:2:92094)
    at ii (/main.67d20ef09a98b096d093.js:152:1981488)
    at Bs (/main.67d20ef09a98b096d093.js:152:2033537)
    at Mu (/main.67d20ef09a98b096d093.js:152:2020811)
```

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by rossipedia** [comment]
This is a regression, thanks for bringing this to our attention. I have a fix in place and should be rolling this out shortly.

**Comment by OiYouYeahYou** [comment]
@rossipedia it's fixed now thank you kindly!

**Comment by OiYouYeahYou** [comment]
@rossipedia seems to have regressed again

**Comment by rossipedia** [comment]
@OiYouYeahYou I'm having trouble reproducing this. What specific URL are you having trouble viewing?

**Comment by OiYouYeahYou** [comment]
Fixed now

**Comment by OiYouYeahYou** [comment]
Actually: here https://hub.docker.com/_/postgres

**Comment by OiYouYeahYou** [comment]
```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at Ae.otFetch (https://cdn.cookielaw.org/scripttemplates/otSDKStub.js:1:8595)
    at Ae.fetchBannerSDKDependency (https://cdn.cookielaw.org/scripttemplates/otSDKStub.js:1:5948)
    at Ae.initConsentSDK (https://cdn.cookielaw.org/scripttemplates/otSDKStub.js:1:5539)
    at new Ae (https://cdn.cookielaw.org/scripttemplates/otSDKStub.js:1:21673)
    at https://cdn.cookielaw.org/scripttemplates/otSDKStub.js:1:21697
    at https://cdn.cookielaw.org/scripttemplates/otSDKStub.js:1:21743
```
