### ISSUE TITLE
Logs don't convert ANSI colour codes

### ISSUE THREAD

**Issue by OmgImAlexis** [docker/hub-feedback#571]
Instead of getting red text I get this.

```
[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mconfigure error[0m[91m 
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m Error: Can't find Python executable "python", you can set the PYTHON env variable.
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:16)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at FSReqWrap.oncomplete (fs.js:82:15)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mSystem[0m[91m Linux 3.13.0-40-generic
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mcommand[0m[91m "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mcwd[0m[91m /src/node_modules/bcrypt
[0m[91mgyp[0m[91m ERR! node -v v5.5.0
```

**Comment by nebuk89** [comment]
Closing due to lack of activity.

**Comment by OmgImAlexis** [comment]
> Closing due to lack of activity.

What activity are you expecting? This is a bug.
