### ISSUE TITLE
Switch building Arch to aarch64 at automated build

### ISSUE THREAD

**Issue by yangwao** [docker/hub-feedback#880]
How I can switch to building Arch to aarch64 from amd64 at hub.docker.com?

Here is the [problematic aarch64 automated build](https://hub.docker.com/r/yangwao/local-npm/builds/bfeqim4x5nrkwk93fjkyaen/)

On my Odroid C2 this build works fine.

```Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-51-generic
Os: linux
BuildTime: 2016-10-27T17:57:25.523154709+00:00
ApiVersion: 1.24
Version: 1.12.3-cs3
GitCommit: 781bb16
Arch: amd64
GoVersion: go1.6.3
Starting build of index.docker.io/yangwao/local-npm:aarch64...
Step 1 : FROM aarch64/node:6.9

 ---> 0afe76847809

Step 2 : MAINTAINER Matej Nemcek <ybdaba@gmail.com>

 ---> Running in 7b69a08c203a

 ---> 0658a6b15338

Removing intermediate container 7b69a08c203a

Step 3 : WORKDIR /src

 ---> Running in 27d3d6c979f7

 ---> d6c41704c4bd

Removing intermediate container 27d3d6c979f7

Step 4 : VOLUME /data

 ---> Running in 1a41d93762ff

 ---> 03aa118bad65

Removing intermediate container 1a41d93762ff

Step 5 : ADD package.json /tmp/package.json

 ---> 8245c0004f15

Removing intermediate container 67f4d573e42e

Step 6 : RUN cd /tmp && npm set progress=false && npm i --no-color

 ---> Running in 24e1dbc9c5f8

[91mpanic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x7ea960, 0xc820128310)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200ef2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea960, 0xc820128310)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200eebf8, 0xc82001a0c8, 0xc8200eed08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7fed1c074728, 0xc820128310)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74f160, 0x900ae8, 0x13, 0x846e88, 0x4, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74f160, 0x900ae8, 0x13, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74f160, 0x900ae8, 0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849d38, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8dfde0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
[0m
Removing intermediate container 24e1dbc9c5f8

The command '/bin/sh -c cd /tmp && npm set progress=false && npm i --no-color' returned a non-zero code: 2```

**Comment by yangwao** [comment]
Will be there support builds for Apple Silicon?
