### ISSUE TITLE
DNS error on /marcoraddatz/homebridge docker image.

### ISSUE THREAD

**Issue by Anuj79** [docker/hub-feedback#982]
hi,
i am trying to run homebridge in docker on a qnap system TS 251 which has intel celron  j1800 CPU with 8 gb ram 
https://hub.docker.com/r/marcoraddatz/homebridge

the docker is crashing on this error. i checked and following daemons were installed but its still giving me this error .. any thoughts on what i can do. i am quite new to docker and homebridge.. any help would be appreciated.

the docker image just continuously reboots. i have tried installing it without any plugins and or config.json but still gives this error 
 
avahi-daemon is already the newest version.
libavahi-compat-libdnssd-dev is already the newest version.

/root/run.sh: line 5: cd: /root/.homebridge: No such file or directory
Logged in as:
root
/root/.homebridge/.env not found.
Default env variables will be used.
Updating Homebridge.
/root/.homebridge/package.json not found.
/root/.homebridge/install.sh not found.
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[3/15/2017, 2:35:41 AM] No plugins found. See the README for information on installing plugins.
[3/15/2017, 2:35:41 AM] config.json (/root/.homebridge/config.json) not found.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ââââââââââââââ
    â 031-45-154 â
    ââââââââââââââ

/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:539:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)

**Comment by Anuj79** [comment]
it sees like the the avahi-daemon service is not starting.. not sure what the error is 
> [FAIL] Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon failed
